"""multi-session days: session_number and started_at

Revision ID: 155303c4e964
Revises: 2d4a056193f4
Create Date: 2026-07-09 13:17:12.230578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '155303c4e964'
down_revision: Union[str, Sequence[str], None] = '2d4a056193f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='1' backfills existing rows as session_number 1 (the
    # only session that could exist per date before this migration) —
    # SQLite needs a default to add a NOT NULL column to a populated table.
    with op.batch_alter_table('training_sessions') as batch_op:
        batch_op.add_column(
            sa.Column(
                'session_number', sa.Integer(), nullable=False, server_default='1'
            )
        )
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(
            'uq_training_sessions_user_date_session_number',
            ['user_id', 'date', 'session_number'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions') as batch_op:
        batch_op.drop_constraint(
            'uq_training_sessions_user_date_session_number', type_='unique'
        )
        batch_op.drop_column('started_at')
        batch_op.drop_column('session_number')
    # ### end Alembic commands ###
