"""work sets and default work set count

Revision ID: 18c9210a7814
Revises: 2a3771d32cba
Create Date: 2026-07-03 14:54:51.460548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18c9210a7814'
down_revision: Union[str, Sequence[str], None] = '2a3771d32cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('hand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grip_type_id', sa.Integer(), nullable=False),
    sa.Column('edge_mm', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['grip_type_id'], ['grip_types.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sets_training_session_id'), 'work_sets', ['training_session_id'], unique=False)
    op.add_column('training_protocols', sa.Column('default_work_sets', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_protocols', 'default_work_sets')
    op.drop_index(op.f('ix_work_sets_training_session_id'), table_name='work_sets')
    op.drop_table('work_sets')
    # ### end Alembic commands ###
