"""training protocol sessions and warmup checks

Revision ID: 2a3771d32cba
Revises: 4cef4aee469d
Create Date: 2026-07-03 14:44:33.098146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a3771d32cba'
down_revision: Union[str, Sequence[str], None] = '4cef4aee469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ramp_percentages', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_work_set_reps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('warmup_step_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('hand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warmup_step_checks_training_session_id'), 'warmup_step_checks', ['training_session_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the single global TrainingProtocol row (ADR-0005): NULL user_id,
    # 50/65/80/90% ramp, 5 base work-set reps.
    op.bulk_insert(
        sa.table(
            'training_protocols',
            sa.column('user_id', sa.Integer()),
            sa.column('ramp_percentages', sa.String()),
            sa.column('base_work_set_reps', sa.Integer()),
        ),
        [{'user_id': None, 'ramp_percentages': '50,65,80,90', 'base_work_set_reps': 5}],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warmup_step_checks_training_session_id'), table_name='warmup_step_checks')
    op.drop_table('warmup_step_checks')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_table('training_protocols')
    # ### end Alembic commands ###
