"""Add session_version to User

Revision ID: 2be767b7e9c2
Revises: 2d4a056193f4
Create Date: 2026-07-09 16:16:49.922185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2be767b7e9c2'
down_revision: Union[str, Sequence[str], None] = '2d4a056193f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_version')
    # ### end Alembic commands ###
