"""add session_max_estimates

Revision ID: 2d4a056193f4
Revises: b41f0a7e2d19
Create Date: 2026-07-07 12:08:31.395357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d4a056193f4'
down_revision: Union[str, Sequence[str], None] = 'b41f0a7e2d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_max_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('hand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grip_type_id', sa.Integer(), nullable=False),
    sa.Column('edge_mm', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grip_type_id'], ['grip_types.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'hand', 'grip_type_id', 'edge_mm', name='uq_session_max_estimates_combo')
    )
    op.create_index(op.f('ix_session_max_estimates_training_session_id'), 'session_max_estimates', ['training_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_max_estimates_training_session_id'), table_name='session_max_estimates')
    op.drop_table('session_max_estimates')
    # ### end Alembic commands ###
