"""Add voided_at to MaxWeightTest

Revision ID: 35b80c457342
Revises: 90ed9e5e7b53
Create Date: 2026-07-09 16:02:46.578463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35b80c457342'
down_revision: Union[str, Sequence[str], None] = '90ed9e5e7b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('max_weight_tests', sa.Column('voided_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('max_weight_tests', 'voided_at')
    # ### end Alembic commands ###
