"""grip types and max weight tests

Revision ID: 4cef4aee469d
Revises: 305c562523ea
Create Date: 2026-07-03 14:29:23.342492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cef4aee469d'
down_revision: Union[str, Sequence[str], None] = '305c562523ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grip_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grip_types_name'), 'grip_types', ['name'], unique=True)
    op.create_table('max_weight_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grip_type_id', sa.Integer(), nullable=False),
    sa.Column('edge_mm', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grip_type_id'], ['grip_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_max_weight_tests_user_id'), 'max_weight_tests', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the starter grip types (frozen copy of STARTER_GRIP_TYPES at the
    # time of this migration; the list can grow later via the admin action).
    op.bulk_insert(
        sa.table('grip_types', sa.column('name', sa.String())),
        [
            {'name': 'half_crimp'},
            {'name': 'full_crimp'},
            {'name': 'open_hand'},
            {'name': 'three_finger_drag'},
            {'name': 'pinch'},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_max_weight_tests_user_id'), table_name='max_weight_tests')
    op.drop_table('max_weight_tests')
    op.drop_index(op.f('ix_grip_types_name'), table_name='grip_types')
    op.drop_table('grip_types')
    # ### end Alembic commands ###
