"""add session_rpe and finished_at to training_sessions

Revision ID: 55d130ba0308
Revises: e5485433cbb8
Create Date: 2026-09-24 12:49:54.249036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55d130ba0308'
down_revision: Union[str, Sequence[str], None] = 'e5485433cbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('session_rpe', sa.Integer(), nullable=True))
    op.add_column('training_sessions', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'finished_at')
    op.drop_column('training_sessions', 'session_rpe')
    # ### end Alembic commands ###
