"""add rest_ends_at to training_sessions

Revision ID: 6f62044ff2d1
Revises: 7535d4def789
Create Date: 2026-09-24 11:02:32.261098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f62044ff2d1'
down_revision: Union[str, Sequence[str], None] = '7535d4def789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('rest_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'rest_ends_at')
    # ### end Alembic commands ###
