"""add progression_settings table

Revision ID: 7535d4def789
Revises: e8a71d4b92c1
Create Date: 2026-08-20 13:10:55.022214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7535d4def789'
down_revision: Union[str, Sequence[str], None] = 'e8a71d4b92c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grip_type_id', sa.Integer(), nullable=True),
    sa.Column('edge_mm', sa.Integer(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rep_min', sa.Integer(), nullable=False),
    sa.Column('rep_max', sa.Integer(), nullable=False),
    sa.Column('max_sets', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grip_type_id'], ['grip_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progression_settings_user_id'), 'progression_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progression_settings_user_id'), table_name='progression_settings')
    op.drop_table('progression_settings')
    # ### end Alembic commands ###
