"""profile prefs and body weight logs

Revision ID: 89e7b6cd84f5
Revises: 8c60bd899b35
Create Date: 2026-07-03 14:17:37.893755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89e7b6cd84f5'
down_revision: Union[str, Sequence[str], None] = '8c60bd899b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_weight_logs_user_id'), 'body_weight_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('unit_pref', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='kg'))
    op.add_column('users', sa.Column('hand_order_pref', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='alternating'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hand_order_pref')
    op.drop_column('users', 'unit_pref')
    op.drop_index(op.f('ix_body_weight_logs_user_id'), table_name='body_weight_logs')
    op.drop_table('body_weight_logs')
    # ### end Alembic commands ###
