"""Add is_deload to training_sessions and pain_reports table

Revision ID: 90ed9e5e7b53
Revises: db20d09ca3be
Create Date: 2026-07-09 15:54:00.923172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90ed9e5e7b53'
down_revision: Union[str, Sequence[str], None] = 'db20d09ca3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pain_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('hand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_reports_training_session_id'), 'pain_reports', ['training_session_id'], unique=False)
    op.add_column('training_sessions', sa.Column('is_deload', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'is_deload')
    op.drop_index(op.f('ix_pain_reports_training_session_id'), table_name='pain_reports')
    op.drop_table('pain_reports')
    # ### end Alembic commands ###
