"""add planned_sets and play combo to training_sessions

Revision ID: c0282a4f3806
Revises: 55d130ba0308
Create Date: 2026-09-24 16:04:22.230297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0282a4f3806'
down_revision: Union[str, Sequence[str], None] = '55d130ba0308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic, then wrapped in batch mode:
    # SQLite can't ALTER a foreign key in place (same as 155303c4e964). ###
    with op.batch_alter_table('training_sessions') as batch_op:
        batch_op.add_column(sa.Column('planned_sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('play_grip_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('play_edge_mm', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_training_sessions_play_grip_type_id_grip_types',
            'grip_types', ['play_grip_type_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic, then wrapped in batch mode ###
    with op.batch_alter_table('training_sessions') as batch_op:
        batch_op.drop_constraint(
            'fk_training_sessions_play_grip_type_id_grip_types', type_='foreignkey'
        )
        batch_op.drop_column('play_edge_mm')
        batch_op.drop_column('play_grip_type_id')
        batch_op.drop_column('planned_sets')
    # ### end Alembic commands ###
