"""dimension_name on grip_types

Revision ID: db20d09ca3be
Revises: 155303c4e964
Create Date: 2026-07-09 15:34:51.118760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db20d09ca3be'
down_revision: Union[str, Sequence[str], None] = '155303c4e964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grip_types', sa.Column('dimension_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='edge depth'))
    op.execute("UPDATE grip_types SET dimension_name = 'block width' WHERE name = 'pinch'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grip_types', 'dimension_name')
    # ### end Alembic commands ###
