"""add rest_sound user setting

Revision ID: e5485433cbb8
Revises: 6f62044ff2d1
Create Date: 2026-09-24 12:21:06.796429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5485433cbb8'
down_revision: Union[str, Sequence[str], None] = '6f62044ff2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rest_sound', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rest_sound')
    # ### end Alembic commands ###
