"""add default_rest_seconds to training_protocols

Revision ID: e8a71d4b92c1
Revises: a623146e0d0d
Create Date: 2026-08-20 12:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8a71d4b92c1'
down_revision: Union[str, Sequence[str], None] = 'a623146e0d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_protocols', sa.Column('default_rest_seconds', sa.Integer(), server_default='180', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_protocols', 'default_rest_seconds')
    # ### end Alembic commands ###
